flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Import"]
node1 --> node2
node3["alias"]
node2 --> node3
node4["Import"]
node3 --> node4
node5["alias"]
node4 --> node5
node6["Import"]
node5 --> node6
node7["alias"]
node6 --> node7
node8["Class FlowchartGenerator"]
node7 --> node8
node9["Function add_node"]
node8 --> node9
node10["AugAssign"]
node9 --> node10
node11["Attribute"]
node10 --> node11
node12["Name"]
node11 --> node12
node13["Load"]
node12 --> node13
node14["Store"]
node13 --> node14
node15["Add"]
node14 --> node15
node16["Constant"]
node15 --> node16
node17["Assign"]
node16 --> node17
node18["Name"]
node17 --> node18
node19["Store"]
node18 --> node19
node20["JoinedStr"]
node19 --> node20
node21["Constant"]
node20 --> node21
node22["FormattedValue"]
node21 --> node22
node23["Attribute"]
node22 --> node23
node24["Name"]
node23 --> node24
node25["Load"]
node24 --> node25
node26["Load"]
node25 --> node26
node27["Expr"]
node26 --> node27
node28["Call"]
node27 --> node28
node29["Attribute"]
node28 --> node29
node30["Attribute"]
node29 --> node30
node31["Name"]
node30 --> node31
node32["Load"]
node31 --> node32
node33["Load"]
node32 --> node33
node34["Load"]
node33 --> node34
node35["JoinedStr"]
node34 --> node35
node36["FormattedValue"]
node35 --> node36
node37["Name"]
node36 --> node37
node38["Load"]
node37 --> node38
node39["Constant"]
node38 --> node39
node40["FormattedValue"]
node39 --> node40
node41["Name"]
node40 --> node41
node42["Load"]
node41 --> node42
node43["Constant"]
node42 --> node43
node44["Return: node_name"]
node43 --> node44
node45["Assign"]
node44 --> node45
node46["Name"]
node45 --> node46
node47["Store"]
node46 --> node47
node48["Constant"]
node47 --> node48
node49["Assign"]
node48 --> node49
node50["Name"]
node49 --> node50
node51["Store"]
node50 --> node51
node52["Constant"]
node51 --> node52
node53["Assign"]
node52 --> node53
node54["Name"]
node53 --> node54
node55["Store"]
node54 --> node55
node56["Constant"]
node55 --> node56
node57["Assign"]
node56 --> node57
node58["Name"]
node57 --> node58
node59["Store"]
node58 --> node59
node60["Constant"]
node59 --> node60
node61["If: __name__ == '__main__'"]
node60 --> node61
node62["Then"]
node61 --> node62
node63["Expr"]
node62 --> node63
node64["Call"]
node63 --> node64
node65["Name"]
node64 --> node65
node66["Load"]
node65 --> node66
End["End"]