flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Import"]
node1 --> node2
node3["alias"]
node2 --> node3
node4["Import"]
node3 --> node4
node5["alias"]
node4 --> node5
node6["Import"]
node5 --> node6
node7["alias"]
node6 --> node7
node8["Class FlowchartGenerator"]
node7 --> node8
node9["Function add_connection"]
node8 --> node9
node10["Expr"]
node9 --> node10
node11["Call"]
node10 --> node11
node12["Attribute"]
node11 --> node12
node13["Attribute"]
node12 --> node13
node14["Name"]
node13 --> node14
node15["Load"]
node14 --> node15
node16["Load"]
node15 --> node16
node17["Load"]
node16 --> node17
node18["JoinedStr"]
node17 --> node18
node19["FormattedValue"]
node18 --> node19
node20["Name"]
node19 --> node20
node21["Load"]
node20 --> node21
node22["Constant"]
node21 --> node22
node23["FormattedValue"]
node22 --> node23
node24["Name"]
node23 --> node24
node25["Load"]
node24 --> node25
node26["Assign"]
node25 --> node26
node27["Name"]
node26 --> node27
node28["Store"]
node27 --> node28
node29["Constant"]
node28 --> node29
node30["Assign"]
node29 --> node30
node31["Name"]
node30 --> node31
node32["Store"]
node31 --> node32
node33["Constant"]
node32 --> node33
node34["Assign"]
node33 --> node34
node35["Name"]
node34 --> node35
node36["Store"]
node35 --> node36
node37["Constant"]
node36 --> node37
node38["Assign"]
node37 --> node38
node39["Name"]
node38 --> node39
node40["Store"]
node39 --> node40
node41["Constant"]
node40 --> node41
node42["If: __name__ == '__main__'"]
node41 --> node42
node43["Then"]
node42 --> node43
node44["Expr"]
node43 --> node44
node45["Call"]
node44 --> node45
node46["Name"]
node45 --> node46
node47["Load"]
node46 --> node47
End["End"]