flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Import"]
node1 --> node2
node3["alias"]
node2 --> node3
node4["Import"]
node3 --> node4
node5["alias"]
node4 --> node5
node6["Import"]
node5 --> node6
node7["alias"]
node6 --> node7
node8["Assign"]
node7 --> node8
node9["Name"]
node8 --> node9
node10["Store"]
node9 --> node10
node11["Constant"]
node10 --> node11
node12["Assign"]
node11 --> node12
node13["Name"]
node12 --> node13
node14["Store"]
node13 --> node14
node15["Constant"]
node14 --> node15
node16["Assign"]
node15 --> node16
node17["Name"]
node16 --> node17
node18["Store"]
node17 --> node18
node19["Constant"]
node18 --> node19
node20["Assign"]
node19 --> node20
node21["Name"]
node20 --> node21
node22["Store"]
node21 --> node22
node23["Constant"]
node22 --> node23
node24["Function print_example_diagrams"]
node23 --> node24
node25["Assign"]
node24 --> node25
node26["Name"]
node25 --> node26
node27["Store"]
node26 --> node27
node28["Call"]
node27 --> node28
node29["Name"]
node28 --> node29
node30["Load"]
node29 --> node30
node31["Expr"]
node30 --> node31
node32["Call"]
node31 --> node32
node33["Name"]
node32 --> node33
node34["Load"]
node33 --> node34
node35["Constant"]
node34 --> node35
node36["Expr"]
node35 --> node36
node37["Call"]
node36 --> node37
node38["Name"]
node37 --> node38
node39["Load"]
node38 --> node39
node40["Call"]
node39 --> node40
node41["Attribute"]
node40 --> node41
node42["Name"]
node41 --> node42
node43["Load"]
node42 --> node43
node44["Load"]
node43 --> node44
node45["Name"]
node44 --> node45
node46["Load"]
node45 --> node46
node47["Assign"]
node46 --> node47
node48["Name"]
node47 --> node48
node49["Store"]
node48 --> node49
node50["Call"]
node49 --> node50
node51["Name"]
node50 --> node51
node52["Load"]
node51 --> node52
node53["Expr"]
node52 --> node53
node54["Call"]
node53 --> node54
node55["Name"]
node54 --> node55
node56["Load"]
node55 --> node56
node57["Constant"]
node56 --> node57
node58["Expr"]
node57 --> node58
node59["Call"]
node58 --> node59
node60["Name"]
node59 --> node60
node61["Load"]
node60 --> node61
node62["Call"]
node61 --> node62
node63["Attribute"]
node62 --> node63
node64["Name"]
node63 --> node64
node65["Load"]
node64 --> node65
node66["Load"]
node65 --> node66
node67["Name"]
node66 --> node67
node68["Load"]
node67 --> node68
node69["Assign"]
node68 --> node69
node70["Name"]
node69 --> node70
node71["Store"]
node70 --> node71
node72["Call"]
node71 --> node72
node73["Name"]
node72 --> node73
node74["Load"]
node73 --> node74
node75["Expr"]
node74 --> node75
node76["Call"]
node75 --> node76
node77["Name"]
node76 --> node77
node78["Load"]
node77 --> node78
node79["Constant"]
node78 --> node79
node80["Expr"]
node79 --> node80
node81["Call"]
node80 --> node81
node82["Name"]
node81 --> node82
node83["Load"]
node82 --> node83
node84["Call"]
node83 --> node84
node85["Attribute"]
node84 --> node85
node86["Name"]
node85 --> node86
node87["Load"]
node86 --> node87
node88["Load"]
node87 --> node88
node89["Name"]
node88 --> node89
node90["Load"]
node89 --> node90
node91["Assign"]
node90 --> node91
node92["Name"]
node91 --> node92
node93["Store"]
node92 --> node93
node94["Call"]
node93 --> node94
node95["Name"]
node94 --> node95
node96["Load"]
node95 --> node96
node97["Expr"]
node96 --> node97
node98["Call"]
node97 --> node98
node99["Name"]
node98 --> node99
node100["Load"]
node99 --> node100
node101["Constant"]
node100 --> node101
node102["Expr"]
node101 --> node102
node103["Call"]
node102 --> node103
node104["Name"]
node103 --> node104
node105["Load"]
node104 --> node105
node106["Call"]
node105 --> node106
node107["Attribute"]
node106 --> node107
node108["Name"]
node107 --> node108
node109["Load"]
node108 --> node109
node110["Load"]
node109 --> node110
node111["Name"]
node110 --> node111
node112["Load"]
node111 --> node112
node113["If: __name__ == '__main__'"]
node112 --> node113
node114["Then"]
node113 --> node114
node115["Expr"]
node114 --> node115
node116["Call"]
node115 --> node116
node117["Name"]
node116 --> node117
node118["Load"]
node117 --> node118
End["End"]