flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Import"]
node1 --> node2
node3["alias"]
node2 --> node3
node4["Import"]
node3 --> node4
node5["alias"]
node4 --> node5
node6["Import"]
node5 --> node6
node7["alias"]
node6 --> node7
node8["Assign"]
node7 --> node8
node9["Name"]
node8 --> node9
node10["Store"]
node9 --> node10
node11["Constant"]
node10 --> node11
node12["Assign"]
node11 --> node12
node13["Name"]
node12 --> node13
node14["Store"]
node13 --> node14
node15["Constant"]
node14 --> node15
node16["Assign"]
node15 --> node16
node17["Name"]
node16 --> node17
node18["Store"]
node17 --> node18
node19["Constant"]
node18 --> node19
node20["Assign"]
node19 --> node20
node21["Name"]
node20 --> node21
node22["Store"]
node21 --> node22
node23["Constant"]
node22 --> node23
node24["Function save_example_diagrams"]
node23 --> node24
node25["Assign"]
node24 --> node25
node26["Name"]
node25 --> node26
node27["Store"]
node26 --> node27
node28["Constant"]
node27 --> node28
node29["Expr"]
node28 --> node29
node30["Call"]
node29 --> node30
node31["Attribute"]
node30 --> node31
node32["Name"]
node31 --> node32
node33["Load"]
node32 --> node33
node34["Load"]
node33 --> node34
node35["Name"]
node34 --> node35
node36["Load"]
node35 --> node36
node37["keyword"]
node36 --> node37
node38["Constant"]
node37 --> node38
node39["Expr"]
node38 --> node39
node40["Call"]
node39 --> node40
node41["Name"]
node40 --> node41
node42["Load"]
node41 --> node42
node43["Constant"]
node42 --> node43
node44["Assign"]
node43 --> node44
node45["Name"]
node44 --> node45
node46["Store"]
node45 --> node46
node47["Call"]
node46 --> node47
node48["Name"]
node47 --> node48
node49["Load"]
node48 --> node49
node50["Assign"]
node49 --> node50
node51["Name"]
node50 --> node51
node52["Store"]
node51 --> node52
node53["Call"]
node52 --> node53
node54["Attribute"]
node53 --> node54
node55["Name"]
node54 --> node55
node56["Load"]
node55 --> node56
node57["Load"]
node56 --> node57
node58["Name"]
node57 --> node58
node59["Load"]
node58 --> node59
node60["Name"]
node59 --> node60
node61["Load"]
node60 --> node61
node62["Expr"]
node61 --> node62
node63["Call"]
node62 --> node63
node64["Name"]
node63 --> node64
node65["Load"]
node64 --> node65
node66["JoinedStr"]
node65 --> node66
node67["Constant"]
node66 --> node67
node68["FormattedValue"]
node67 --> node68
node69["Call"]
node68 --> node69
node70["Attribute"]
node69 --> node70
node71["Constant"]
node70 --> node71
node72["Load"]
node71 --> node72
node73["Name"]
node72 --> node73
node74["Load"]
node73 --> node74
node75["Assign"]
node74 --> node75
node76["Name"]
node75 --> node76
node77["Store"]
node76 --> node77
node78["Call"]
node77 --> node78
node79["Name"]
node78 --> node79
node80["Load"]
node79 --> node80
node81["Assign"]
node80 --> node81
node82["Name"]
node81 --> node82
node83["Store"]
node82 --> node83
node84["Call"]
node83 --> node84
node85["Attribute"]
node84 --> node85
node86["Name"]
node85 --> node86
node87["Load"]
node86 --> node87
node88["Load"]
node87 --> node88
node89["Name"]
node88 --> node89
node90["Load"]
node89 --> node90
node91["Name"]
node90 --> node91
node92["Load"]
node91 --> node92
node93["Expr"]
node92 --> node93
node94["Call"]
node93 --> node94
node95["Name"]
node94 --> node95
node96["Load"]
node95 --> node96
node97["JoinedStr"]
node96 --> node97
node98["Constant"]
node97 --> node98
node99["FormattedValue"]
node98 --> node99
node100["Call"]
node99 --> node100
node101["Attribute"]
node100 --> node101
node102["Constant"]
node101 --> node102
node103["Load"]
node102 --> node103
node104["Name"]
node103 --> node104
node105["Load"]
node104 --> node105
node106["Assign"]
node105 --> node106
node107["Name"]
node106 --> node107
node108["Store"]
node107 --> node108
node109["Call"]
node108 --> node109
node110["Name"]
node109 --> node110
node111["Load"]
node110 --> node111
node112["Assign"]
node111 --> node112
node113["Name"]
node112 --> node113
node114["Store"]
node113 --> node114
node115["Call"]
node114 --> node115
node116["Attribute"]
node115 --> node116
node117["Name"]
node116 --> node117
node118["Load"]
node117 --> node118
node119["Load"]
node118 --> node119
node120["Name"]
node119 --> node120
node121["Load"]
node120 --> node121
node122["Name"]
node121 --> node122
node123["Load"]
node122 --> node123
node124["Expr"]
node123 --> node124
node125["Call"]
node124 --> node125
node126["Name"]
node125 --> node126
node127["Load"]
node126 --> node127
node128["JoinedStr"]
node127 --> node128
node129["Constant"]
node128 --> node129
node130["FormattedValue"]
node129 --> node130
node131["Call"]
node130 --> node131
node132["Attribute"]
node131 --> node132
node133["Constant"]
node132 --> node133
node134["Load"]
node133 --> node134
node135["Name"]
node134 --> node135
node136["Load"]
node135 --> node136
node137["Assign"]
node136 --> node137
node138["Name"]
node137 --> node138
node139["Store"]
node138 --> node139
node140["Call"]
node139 --> node140
node141["Name"]
node140 --> node141
node142["Load"]
node141 --> node142
node143["Assign"]
node142 --> node143
node144["Name"]
node143 --> node144
node145["Store"]
node144 --> node145
node146["Call"]
node145 --> node146
node147["Attribute"]
node146 --> node147
node148["Name"]
node147 --> node148
node149["Load"]
node148 --> node149
node150["Load"]
node149 --> node150
node151["Name"]
node150 --> node151
node152["Load"]
node151 --> node152
node153["Name"]
node152 --> node153
node154["Load"]
node153 --> node154
node155["Expr"]
node154 --> node155
node156["Call"]
node155 --> node156
node157["Name"]
node156 --> node157
node158["Load"]
node157 --> node158
node159["JoinedStr"]
node158 --> node159
node160["Constant"]
node159 --> node160
node161["FormattedValue"]
node160 --> node161
node162["Call"]
node161 --> node162
node163["Attribute"]
node162 --> node163
node164["Constant"]
node163 --> node164
node165["Load"]
node164 --> node165
node166["Name"]
node165 --> node166
node167["Load"]
node166 --> node167
node168["Function save_example_diagrams"]
node167 --> node168
node169["Expr"]
node168 --> node169
node170["Call"]
node169 --> node170
node171["Name"]
node170 --> node171
node172["Load"]
node171 --> node172
node173["Constant"]
node172 --> node173
node174["Assign"]
node173 --> node174
node175["Name"]
node174 --> node175
node176["Store"]
node175 --> node176
node177["Constant"]
node176 --> node177
node178["Assign"]
node177 --> node178
node179["Name"]
node178 --> node179
node180["Store"]
node179 --> node180
node181["Call"]
node180 --> node181
node182["Name"]
node181 --> node182
node183["Load"]
node182 --> node183
node184["Assign"]
node183 --> node184
node185["Name"]
node184 --> node185
node186["Store"]
node185 --> node186
node187["Call"]
node186 --> node187
node188["Attribute"]
node187 --> node188
node189["Name"]
node188 --> node189
node190["Load"]
node189 --> node190
node191["Load"]
node190 --> node191
node192["Name"]
node191 --> node192
node193["Load"]
node192 --> node193
node194["Constant"]
node193 --> node194
node195["Expr"]
node194 --> node195
node196["Call"]
node195 --> node196
node197["Name"]
node196 --> node197
node198["Load"]
node197 --> node198
node199["JoinedStr"]
node198 --> node199
node200["Constant"]
node199 --> node200
node201["FormattedValue"]
node200 --> node201
node202["Call"]
node201 --> node202
node203["Attribute"]
node202 --> node203
node204["Constant"]
node203 --> node204
node205["Load"]
node204 --> node205
node206["Name"]
node205 --> node206
node207["Load"]
node206 --> node207
node208["Assign"]
node207 --> node208
node209["Name"]
node208 --> node209
node210["Store"]
node209 --> node210
node211["Constant"]
node210 --> node211
node212["Assign"]
node211 --> node212
node213["Name"]
node212 --> node213
node214["Store"]
node213 --> node214
node215["Call"]
node214 --> node215
node216["Name"]
node215 --> node216
node217["Load"]
node216 --> node217
node218["Assign"]
node217 --> node218
node219["Name"]
node218 --> node219
node220["Store"]
node219 --> node220
node221["Call"]
node220 --> node221
node222["Attribute"]
node221 --> node222
node223["Name"]
node222 --> node223
node224["Load"]
node223 --> node224
node225["Load"]
node224 --> node225
node226["Name"]
node225 --> node226
node227["Load"]
node226 --> node227
node228["Constant"]
node227 --> node228
node229["Expr"]
node228 --> node229
node230["Call"]
node229 --> node230
node231["Name"]
node230 --> node231
node232["Load"]
node231 --> node232
node233["JoinedStr"]
node232 --> node233
node234["Constant"]
node233 --> node234
node235["FormattedValue"]
node234 --> node235
node236["Call"]
node235 --> node236
node237["Attribute"]
node236 --> node237
node238["Constant"]
node237 --> node238
node239["Load"]
node238 --> node239
node240["Name"]
node239 --> node240
node241["Load"]
node240 --> node241
node242["Assign"]
node241 --> node242
node243["Name"]
node242 --> node243
node244["Store"]
node243 --> node244
node245["Constant"]
node244 --> node245
node246["Assign"]
node245 --> node246
node247["Name"]
node246 --> node247
node248["Store"]
node247 --> node248
node249["Call"]
node248 --> node249
node250["Name"]
node249 --> node250
node251["Load"]
node250 --> node251
node252["Assign"]
node251 --> node252
node253["Name"]
node252 --> node253
node254["Store"]
node253 --> node254
node255["Call"]
node254 --> node255
node256["Attribute"]
node255 --> node256
node257["Name"]
node256 --> node257
node258["Load"]
node257 --> node258
node259["Load"]
node258 --> node259
node260["Name"]
node259 --> node260
node261["Load"]
node260 --> node261
node262["Constant"]
node261 --> node262
node263["Expr"]
node262 --> node263
node264["Call"]
node263 --> node264
node265["Name"]
node264 --> node265
node266["Load"]
node265 --> node266
node267["JoinedStr"]
node266 --> node267
node268["Constant"]
node267 --> node268
node269["FormattedValue"]
node268 --> node269
node270["Call"]
node269 --> node270
node271["Attribute"]
node270 --> node271
node272["Constant"]
node271 --> node272
node273["Load"]
node272 --> node273
node274["Name"]
node273 --> node274
node275["Load"]
node274 --> node275
node276["Assign"]
node275 --> node276
node277["Name"]
node276 --> node277
node278["Store"]
node277 --> node278
node279["Constant"]
node278 --> node279
node280["Assign"]
node279 --> node280
node281["Name"]
node280 --> node281
node282["Store"]
node281 --> node282
node283["Call"]
node282 --> node283
node284["Name"]
node283 --> node284
node285["Load"]
node284 --> node285
node286["Assign"]
node285 --> node286
node287["Name"]
node286 --> node287
node288["Store"]
node287 --> node288
node289["Call"]
node288 --> node289
node290["Attribute"]
node289 --> node290
node291["Name"]
node290 --> node291
node292["Load"]
node291 --> node292
node293["Load"]
node292 --> node293
node294["Name"]
node293 --> node294
node295["Load"]
node294 --> node295
node296["Constant"]
node295 --> node296
node297["Expr"]
node296 --> node297
node298["Call"]
node297 --> node298
node299["Name"]
node298 --> node299
node300["Load"]
node299 --> node300
node301["JoinedStr"]
node300 --> node301
node302["Constant"]
node301 --> node302
node303["FormattedValue"]
node302 --> node303
node304["Call"]
node303 --> node304
node305["Attribute"]
node304 --> node305
node306["Constant"]
node305 --> node306
node307["Load"]
node306 --> node307
node308["Name"]
node307 --> node308
node309["Load"]
node308 --> node309
node310["Assign"]
node309 --> node310
node311["Name"]
node310 --> node311
node312["Store"]
node311 --> node312
node313["Constant"]
node312 --> node313
node314["Assign"]
node313 --> node314
node315["Name"]
node314 --> node315
node316["Store"]
node315 --> node316
node317["Call"]
node316 --> node317
node318["Name"]
node317 --> node318
node319["Load"]
node318 --> node319
node320["Assign"]
node319 --> node320
node321["Name"]
node320 --> node321
node322["Store"]
node321 --> node322
node323["Call"]
node322 --> node323
node324["Attribute"]
node323 --> node324
node325["Name"]
node324 --> node325
node326["Load"]
node325 --> node326
node327["Load"]
node326 --> node327
node328["Name"]
node327 --> node328
node329["Load"]
node328 --> node329
node330["Constant"]
node329 --> node330
node331["Expr"]
node330 --> node331
node332["Call"]
node331 --> node332
node333["Name"]
node332 --> node333
node334["Load"]
node333 --> node334
node335["JoinedStr"]
node334 --> node335
node336["Constant"]
node335 --> node336
node337["FormattedValue"]
node336 --> node337
node338["Call"]
node337 --> node338
node339["Attribute"]
node338 --> node339
node340["Constant"]
node339 --> node340
node341["Load"]
node340 --> node341
node342["Name"]
node341 --> node342
node343["Load"]
node342 --> node343
node344["If: __name__ == '__main__'"]
node343 --> node344
node345["Then"]
node344 --> node345
node346["Expr"]
node345 --> node346
node347["Call"]
node346 --> node347
node348["Name"]
node347 --> node348
node349["Load"]
node348 --> node349
End["End"]