flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Import"]
node1 --> node2
node3["alias"]
node2 --> node3
node4["Import"]
node1 --> node4
node5["alias"]
node4 --> node5
node6["Import"]
node1 --> node6
node7["alias"]
node6 --> node7
node8["Class FlowchartGenerator"]
node1 --> node8
node9["Function visit_Continue"]
node8 --> node9
node10["If: self.loop_start_node"]
node9 --> node10
node11["Then"]
node10 --> node11
node12["Assign"]
node11 --> node12
node13["Name"]
node12 --> node13
node14["Store"]
node13 --> node14
node15["Call"]
node12 --> node15
node16["Attribute"]
node15 --> node16
node17["Name"]
node16 --> node17
node18["Load"]
node17 --> node18
node19["Load"]
node16 --> node19
node20["Constant"]
node15 --> node20
node21["Expr"]
node11 --> node21
node22["Call"]
node21 --> node22
node23["Attribute"]
node22 --> node23
node24["Name"]
node23 --> node24
node25["Load"]
node24 --> node25
node26["Load"]
node23 --> node26
node27["Attribute"]
node22 --> node27
node28["Name"]
node27 --> node28
node29["Load"]
node28 --> node29
node30["Load"]
node27 --> node30
node31["Name"]
node22 --> node31
node32["Load"]
node31 --> node32
node33["Expr"]
node11 --> node33
node34["Call"]
node33 --> node34
node35["Attribute"]
node34 --> node35
node36["Name"]
node35 --> node36
node37["Load"]
node36 --> node37
node38["Load"]
node35 --> node38
node39["Name"]
node34 --> node39
node40["Load"]
node39 --> node40
node41["Attribute"]
node34 --> node41
node42["Name"]
node41 --> node42
node43["Load"]
node42 --> node43
node44["Load"]
node41 --> node44
node45["Assign"]
node11 --> node45
node46["Name"]
node45 --> node46
node47["Store"]
node46 --> node47
node48["Call"]
node45 --> node48
node49["Attribute"]
node48 --> node49
node50["Name"]
node49 --> node50
node51["Load"]
node50 --> node51
node52["Load"]
node49 --> node52
node53["Constant"]
node48 --> node53
node54["Assign"]
node11 --> node54
node55["Attribute"]
node54 --> node55
node56["Name"]
node55 --> node56
node57["Load"]
node56 --> node57
node58["Store"]
node55 --> node58
node59["Name"]
node54 --> node59
node60["Load"]
node59 --> node60
node61["Else"]
node10 --> node61
node62["Assign"]
node61 --> node62
node63["Name"]
node62 --> node63
node64["Store"]
node63 --> node64
node65["Call"]
node62 --> node65
node66["Attribute"]
node65 --> node66
node67["Name"]
node66 --> node67
node68["Load"]
node67 --> node68
node69["Load"]
node66 --> node69
node70["Constant"]
node65 --> node70
node71["Expr"]
node61 --> node71
node72["Call"]
node71 --> node72
node73["Attribute"]
node72 --> node73
node74["Name"]
node73 --> node74
node75["Load"]
node74 --> node75
node76["Load"]
node73 --> node76
node77["Attribute"]
node72 --> node77
node78["Name"]
node77 --> node78
node79["Load"]
node78 --> node79
node80["Load"]
node77 --> node80
node81["Name"]
node72 --> node81
node82["Load"]
node81 --> node82
node83["Assign"]
node61 --> node83
node84["Attribute"]
node83 --> node84
node85["Name"]
node84 --> node85
node86["Load"]
node85 --> node86
node87["Store"]
node84 --> node87
node88["Name"]
node83 --> node88
node89["Load"]
node88 --> node89
node90["Assign"]
node10 --> node90
node91["Name"]
node90 --> node91
node92["Store"]
node91 --> node92
node93["Constant"]
node90 --> node93
node94["Assign"]
node10 --> node94
node95["Name"]
node94 --> node95
node96["Store"]
node95 --> node96
node97["Constant"]
node94 --> node97
node98["Assign"]
node10 --> node98
node99["Name"]
node98 --> node99
node100["Store"]
node99 --> node100
node101["Constant"]
node98 --> node101
node102["Assign"]
node10 --> node102
node103["Name"]
node102 --> node103
node104["Store"]
node103 --> node104
node105["Constant"]
node102 --> node105
node106["If: __name__ == '__main__'"]
node10 --> node106
node107["Then"]
node106 --> node107
node108["Expr"]
node107 --> node108
node109["Call"]
node108 --> node109
node110["Name"]
node109 --> node110
node111["Load"]
node110 --> node111
End["End"]