flowchart TD
Start["Start"]
node1["Class FlowchartGenerator"]
Start --> node1
node2["Function __init__"]
node1 --> node2
node3["If: __name__ == '__main__'"]
node2 --> node3
node4["Then"]
node3 --> node4
End["End"]