flowchart TD
Start["Start"]
node1["Class FlowchartGenerator"]
Start --> node1
node2["Function generate_mermaid_flowchart"]
node1 --> node2
node3["Return: '\n'.join(self.flowchart)"]
node2 --> node3
node4["If: __name__ == '__main__'"]
node3 --> node4
node5["Then"]
node4 --> node5
End["End"]