flowchart TD
Start["Start"]
node1["Class FlowchartGenerator"]
Start --> node1
node2["Function visit_While"]
node1 --> node2
node3["For: n in node.body"]
node2 --> node3
node4["Loop Body"]
node3 --> node4
node5["After Loop"]
node4 --> node3
node3 --> node5
node6["If: node.orelse"]
node5 --> node6
node7["Then"]
node6 --> node7
node8["For: n in node.orelse"]
node7 --> node8
node9["Loop Body"]
node8 --> node9
node10["After Loop"]
node9 --> node8
node8 --> node10
node11["If: __name__ == '__main__'"]
node6 --> node11
node12["Then"]
node11 --> node12
End["End"]