flowchart TD
Start["Start"]
node1["Function save_example_diagrams"]
Start --> node1
node2["Function save_example_diagrams"]
node1 --> node2
node3["If: __name__ == '__main__'"]
node2 --> node3
node4["Then"]
node3 --> node4
End["End"]