flowchart TD
Start["Start"]
node1["Function multiply"]
Start --> node1
node2["If: x == 0"]
node1 --> node2
node3["Then"]
node2 --> node3
node4["Return: 0"]
node3 --> node4
node5["Return: self.value"]
node2 --> node5
End["End"]