flowchart TD
Start["Start"]
node1["Function visit_Continue"]
Start --> node1
node2["If: self.loop_start_node"]
node1 --> node2
node3["Then"]
node2 --> node3
node4["Else"]
node2 --> node4
End["End"]
node2 --> End