flowchart TD
Start["Start"]
node1["Module"]
Start --> node1
node2["Class Calculator"]
node1 --> node2
node3["Function __init__"]
node2 --> node3
node4["Assign"]
node3 --> node4
node5["Attribute"]
node4 --> node5
node6["Name"]
node5 --> node6
node7["Load"]
node6 --> node7
node8["Store"]
node7 --> node8
node9["Name"]
node8 --> node9
node10["Load"]
node9 --> node10
node11["Function add"]
node10 --> node11
node12["AugAssign"]
node11 --> node12
node13["Attribute"]
node12 --> node13
node14["Name"]
node13 --> node14
node15["Load"]
node14 --> node15
node16["Store"]
node15 --> node16
node17["Add"]
node16 --> node17
node18["Name"]
node17 --> node18
node19["Load"]
node18 --> node19
node20["Return: self.value"]
node19 --> node20
node21["Function subtract"]
node20 --> node21
node22["AugAssign"]
node21 --> node22
node23["Attribute"]
node22 --> node23
node24["Name"]
node23 --> node24
node25["Load"]
node24 --> node25
node26["Store"]
node25 --> node26
node27["Sub"]
node26 --> node27
node28["Name"]
node27 --> node28
node29["Load"]
node28 --> node29
node30["Return: self.value"]
node29 --> node30
node31["Function multiply"]
node30 --> node31
node32["If: x == 0"]
node31 --> node32
node33["Then"]
node32 --> node33
node34["Return: 0"]
node33 --> node34
node35["AugAssign"]
node32 --> node35
node36["Attribute"]
node35 --> node36
node37["Name"]
node36 --> node37
node38["Load"]
node37 --> node38
node39["Store"]
node38 --> node39
node40["Mult"]
node39 --> node40
node41["Name"]
node40 --> node41
node42["Load"]
node41 --> node42
node43["Return: self.value"]
node42 --> node43
End["End"]